### ISSUE TITLE
Embed videos?

### ISSUE THREAD

**Issue by mkoai** [QuiteStochastic/cs373-idb#61]
Character example: https://www.youtube.com/watch?v=5FoXU1pNr7g
Organization example: https://www.youtube.com/watch?v=Wm0ikHOkGOY
Location example: NOT SURE. Maybe more images?
Event example: https://www.youtube.com/watch?v=ifx0Fg_drBI
Episode example: https://www.youtube.com/watch?v=LCpWf_ybG3Y

Tried to look for official HBO videos. Couldn't find any such videos for LOCATIONS or EVENTS.

**Comment by mkoai** [comment]
Look up YouTube's API? Might have to store URLs in database. Get back to back-end!

**Comment by tvarney** [comment]
At this point this would require more changes than we are comfortable implementing since the deadline is so close.
